import 'package:fluship/services/pipeline/pipeline.dart';
import 'package:fluship/features/pipeline/models/pipeline_step_view.dart';
import 'package:intl/intl.dart';

import 'report_html_theme.dart';

class BuildReportStepResult {
  const BuildReportStepResult({
    required this.elapsed,
    required this.success,
    required this.name,
  });

  final Duration? elapsed;
  final bool success;
  final String name;
}

class BuildReportHtmlBuilder {
  const BuildReportHtmlBuilder();

  String build({
    required List<BuildReportStepResult> steps,
    required ReportHtmlTheme theme,
    required String totalElapsed,
    required String buildNumber,
    required String platforms,
    required bool success,
    required String appName,
    required String version,
  }) {
    final statusColor = success ? theme.success : theme.error;
    final statusText = success ? 'Build Succeeded' : 'Build Failed';
    final statusEmoji = success ? '✓' : '✗';
    final nowStr = DateFormat('MMM d, yyyy · HH:mm').format(DateTime.now());

    final stepRows = StringBuffer();
    for (final step in steps) {
      stepRows.write(_stepRow(step, theme));
    }

    final escapedApp = _escape(appName);
    final escapedVersion = _escape(version);
    final escapedBuild = _escape(buildNumber);

    return '${theme.bodyOpen}'
        '${_htmlHeader('Build Report &mdash; v$escapedVersion+$escapedBuild', escapedApp, theme)}'
        "${_htmlBanner('$statusEmoji&ensp;$statusText', statusColor)}"
        '<div style="background:${theme.cardBg};padding:16px 20px;${theme.borderLr}">'
        '<table style="width:100%;border-collapse:collapse;">'
        '${_summaryRow('Version', 'v$version+$buildNumber', theme, bold: true)}'
        '${_summaryRow('Platforms', platforms, theme)}'
        '${_summaryRow('Total Time', totalElapsed, theme, color: theme.accent, bold: true)}'
        '${_summaryRow('Date', nowStr, theme)}'
        '</table></div>'
        '<div style="background:${theme.cardBg};${theme.borderLr}">'
        '<div style="padding:12px 20px 6px;border-top:1px solid ${theme.cardBorder};">'
        '<h2 ${theme.sectionH2Styled}>Pipeline Steps</h2></div>'
        '<table style="width:100%;border-collapse:collapse;">'
        '<tr style="background:${theme.bg};">'
        '<th ${theme.thStyleAligned('left')}>Step</th>'
        '<th ${theme.thStyleAligned('center')}>Status</th>'
        '<th ${theme.thStyleAligned('right')}>Time</th>'
        '</tr>$stepRows</table></div>'
        '${_htmlFooter(escapedApp, theme)}'
        '${ReportHtmlTheme.bodyClose}';
  }

  List<BuildReportStepResult> stepsFromPipelineViews(
    List<PipelineStepView> views,
  ) {
    return views
        .where((v) => v.status != PipelineStepStatus.pending)
        .map(
          (v) => BuildReportStepResult(
            success: v.status == PipelineStepStatus.completed,
            elapsed: v.elapsed,
            name: v.name,
          ),
        )
        .toList();
  }

  String _stepRow(BuildReportStepResult step, ReportHtmlTheme theme) {
    final elapsed = step.elapsed;
    final elapsedText = elapsed == null
        ? '—'
        : PipelineUtils.formatPipelineDuration(elapsed);

    return '<tr>'
        '<td style="padding:7px 12px;border-bottom:1px solid ${theme.cardBorder};'
        'color:${theme.text};font-size:13px;">${_escape(step.name)}</td>'
        '<td style="padding:7px 12px;border-bottom:1px solid ${theme.cardBorder};'
        'text-align:center;">${_statusBadge(step.success, theme)}</td>'
        '<td style="padding:7px 12px;border-bottom:1px solid ${theme.cardBorder};'
        'color:${theme.section};font-size:12px;text-align:right;'
        'font-family:Consolas,monospace;">$elapsedText</td>'
        '</tr>';
  }

  String _htmlHeader(String subtitle, String appName, ReportHtmlTheme theme) {
    return '<div style="background:linear-gradient(135deg,${theme.accent},${theme.section});'
        'border-radius:12px 12px 0 0;padding:22px 20px;text-align:center;">'
        '<h1 style="margin:0;font-size:22px;color:#fff;letter-spacing:-0.3px;">'
        '⚡ $appName</h1>'
        '<p style="margin:4px 0 0;font-size:13px;color:rgba(255,255,255,0.8);font-weight:500;">'
        '$subtitle</p></div>';
  }

  String _htmlFooter(String appName, ReportHtmlTheme theme) {
    return '<div style="background:${theme.cardBg};border-radius:0 0 12px 12px;'
        '${theme.borderLr}border-bottom:1px solid ${theme.cardBorder};'
        'padding:14px 20px;text-align:center;">'
        '<p style="margin:0 0 2px;font-size:10px;color:${theme.textDim};">'
        'Generated by <strong style="color:${theme.accent};">$appName</strong>'
        ' v${ReportHtmlTheme.flushipVersion}</p>'
        '<p style="margin:0;font-size:10px;color:${theme.section};">'
        'Made with ❤️ by Senpai</p></div>';
  }

  String _htmlBanner(String text, String bg) {
    return '<div style="background:$bg;padding:9px 20px;text-align:center;">'
        '<span style="color:#020617;font-size:14px;font-weight:700;'
        'letter-spacing:0.2px;">$text</span></div>';
  }

  String _summaryRow(
    String label,
    String value,
    ReportHtmlTheme theme, {
    String? color,
    bool bold = false,
  }) {
    final textColor = color ?? theme.text;
    final weight = bold ? 'font-weight:600;' : '';
    return '<tr><td style="padding:4px 0;color:${theme.textDim};font-size:12px;width:100px;">'
        '${_escape(label)}</td>'
        '<td style="padding:4px 0;color:$textColor;font-size:13px;$weight">'
        '${_escape(value)}</td></tr>';
  }

  String _statusBadge(bool ok, ReportHtmlTheme theme) {
    if (ok) {
      return '<span style="display:inline-block;background:#065f46;color:${theme.success};'
          'padding:1px 8px;border-radius:20px;font-size:11px;font-weight:600;">'
          '✓ Passed</span>';
    }

    return '<span style="display:inline-block;background:#7f1d1d;color:${theme.error};'
        'padding:1px 8px;border-radius:20px;font-size:11px;font-weight:600;">'
        '✗ Failed</span>';
  }

  String _escape(String value) {
    return value
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&#39;');
  }
}
