import 'package:fluship/services/pipeline/pipeline.dart';
import 'package:fluship/features/pipeline/models/pipeline_step_view.dart';
import 'package:intl/intl.dart';

import 'report_html_theme.dart';

class BuildReportStepResult {
  const BuildReportStepResult({
    required this.elapsed,
    required this.success,
    required this.name,
  });

  final Duration? elapsed;
  final bool success;
  final String name;
}

class BuildReportHtmlBuilder {
  const BuildReportHtmlBuilder();

  String build({
    required List<BuildReportStepResult> steps,
    required String totalElapsed,
    required String platforms,
    required String buildNumber,
    required bool success,
    required String appName,
    required String version,
  }) {
    final statusColor = success ? ReportHtmlTheme.success : ReportHtmlTheme.error;
    final statusText = success ? 'Build Succeeded' : 'Build Failed';
    final statusEmoji = success ? '✓' : '✗';
    final nowStr = DateFormat('MMM d, yyyy · HH:mm').format(DateTime.now());

    final stepRows = steps.map(_stepRow).join();
    final escapedApp = _escape(appName);
    final escapedVersion = _escape(version);
    final escapedBuild = _escape(buildNumber);

    return '${ReportHtmlTheme.bodyOpen}'
        '${_htmlHeader('Build Report &mdash; v$escapedVersion+$escapedBuild', escapedApp)}'
        "${_htmlBanner('$statusEmoji&ensp;$statusText', statusColor)}"
        '<div style="background:${ReportHtmlTheme.cardBg};padding:16px 20px;${ReportHtmlTheme.borderLr}">'
        '<table style="width:100%;border-collapse:collapse;">'
        '${_summaryRow('Version', 'v$version+$buildNumber', bold: true)}'
        '${_summaryRow('Platforms', platforms)}'
        '${_summaryRow('Total Time', totalElapsed, color: ReportHtmlTheme.accent, bold: true)}'
        '${_summaryRow('Date', nowStr)}'
        '</table></div>'
        '<div style="background:${ReportHtmlTheme.cardBg};${ReportHtmlTheme.borderLr}">'
        '<div style="padding:12px 20px 6px;border-top:1px solid ${ReportHtmlTheme.cardBorder};">'
        '<h2 ${ReportHtmlTheme.sectionH2}>Pipeline Steps</h2></div>'
        '<table style="width:100%;border-collapse:collapse;">'
        '<tr style="background:${ReportHtmlTheme.bg};">'
        '<th ${ReportHtmlTheme.thStyle.replaceAll('{align}', 'left')}>Step</th>'
        '<th ${ReportHtmlTheme.thStyle.replaceAll('{align}', 'center')}>Status</th>'
        '<th ${ReportHtmlTheme.thStyle.replaceAll('{align}', 'right')}>Time</th>'
        '</tr>$stepRows</table></div>'
        '${_htmlFooter(escapedApp)}'
        '${ReportHtmlTheme.bodyClose}';
  }

  List<BuildReportStepResult> stepsFromPipelineViews(
    List<PipelineStepView> views,
  ) {
    return views
        .where((view) => view.status != PipelineStepStatus.pending)
        .map(
          (view) => BuildReportStepResult(
            name: view.name,
            elapsed: view.elapsed,
            success: view.status == PipelineStepStatus.completed,
          ),
        )
        .toList();
  }

  String _stepRow(BuildReportStepResult step) {
    final elapsed = step.elapsed;
    final elapsedText = elapsed == null
        ? '—'
        : PipelineUtils.formatPipelineDuration(elapsed);

    return '<tr>'
        '<td style="padding:7px 12px;border-bottom:1px solid ${ReportHtmlTheme.cardBorder};'
        'color:#e2e8f0;font-size:13px;">${_escape(step.name)}</td>'
        '<td style="padding:7px 12px;border-bottom:1px solid ${ReportHtmlTheme.cardBorder};'
        'text-align:center;">${_statusBadge(step.success)}</td>'
        '<td style="padding:7px 12px;border-bottom:1px solid ${ReportHtmlTheme.cardBorder};'
        'color:${ReportHtmlTheme.section};font-size:12px;text-align:right;'
        'font-family:Consolas,monospace;">$elapsedText</td>'
        '</tr>';
  }

  String _htmlHeader(String subtitle, String appName) {
    return '<div style="background:linear-gradient(135deg,#0284c7,${ReportHtmlTheme.accent});'
        'border-radius:12px 12px 0 0;padding:22px 20px;text-align:center;">'
        '<h1 style="margin:0;font-size:22px;color:#fff;letter-spacing:-0.3px;">'
        '⚡ $appName</h1>'
        '<p style="margin:4px 0 0;font-size:13px;color:rgba(255,255,255,0.8);font-weight:500;">'
        '$subtitle</p></div>';
  }

  String _htmlFooter(String appName) {
    return '<div style="background:${ReportHtmlTheme.cardBg};border-radius:0 0 12px 12px;'
        '${ReportHtmlTheme.borderLr}border-bottom:1px solid ${ReportHtmlTheme.cardBorder};'
        'padding:14px 20px;text-align:center;">'
        '<p style="margin:0 0 2px;font-size:10px;color:#475569;">'
        'Generated by <strong style="color:${ReportHtmlTheme.accent};">$appName</strong>'
        ' v${ReportHtmlTheme.flushipVersion}</p>'
        '<p style="margin:0;font-size:10px;color:#334155;">'
        'Made with ❤️ by Senpai</p></div>';
  }

  String _htmlBanner(String text, String bg) {
    return '<div style="background:$bg;padding:9px 20px;text-align:center;">'
        '<span style="color:#020617;font-size:14px;font-weight:700;'
        'letter-spacing:0.2px;">$text</span></div>';
  }

  String _summaryRow(
    String label,
    String value, {
    String color = '#e2e8f0',
    bool bold = false,
  }) {
    final weight = bold ? 'font-weight:600;' : '';
    return '<tr><td style="padding:4px 0;color:#64748b;font-size:12px;width:100px;">'
        '${_escape(label)}</td>'
        '<td style="padding:4px 0;color:$color;font-size:13px;$weight">'
        '${_escape(value)}</td></tr>';
  }

  String _statusBadge(bool ok) {
    if (ok) {
      return '<span style="display:inline-block;background:#065f46;color:#34d399;'
          'padding:1px 8px;border-radius:20px;font-size:11px;font-weight:600;">'
          '✓ Passed</span>';
    }

    return '<span style="display:inline-block;background:#7f1d1d;color:#fca5a5;'
        'padding:1px 8px;border-radius:20px;font-size:11px;font-weight:600;">'
        '✗ Failed</span>';
  }

  String _escape(String value) {
    return value
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;');
  }
}
